name: appsync_to_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  json_annotation: any

  

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  json_serializable: any
  build_runner: any
